### ISSUE TITLE
Disable weather widget

### ISSUE THREAD

**Issue by dharabor** [icaps25/icaps25.github.io#15]
The weather widget eats up valuable screen real-estate. I propose we disable it, until some weeks before the conference (i.e., when it becomes relevant).

**Comment by dharabor** [comment]
For discussion, @miquelramirez @nirlipo @ssardina

**Comment by miquelramirez** [comment]
> The weather widget eats up valuable screen real-estate. I propose we disable it, until some weeks before the conference (i.e., when it becomes relevant).

Yep, I concur

**Comment by ssardina** [comment]
agree too, done, removed!

![image](https://github.com/user-attachments/assets/18f1e5dc-138c-4620-8b8c-bb6c577b03da)

We'll enabled closer to the conference
