### ISSUE TITLE
Links are not distinguished from regular text

### ISSUE THREAD

**Issue by dharabor** [icaps25/icaps25.github.io#16]
Suggest we modify the style so these are blue, like everywhere else on the web.

**Comment by dharabor** [comment]
For discussion @miquelramirez

**Comment by miquelramirez** [comment]
I was thinking the same. The CSS etc. needs some tweaks.

In the meantime I was thinking of using *this style* rather than **this other one**.

**Comment by miquelramirez** [comment]
Just merged a PR (#17) with the change of Markdown style. Styles will need to be revisited when something is done about the website's CSS.

**Comment by nirlipo** [comment]
Working on a fix for this. PR soon to be sent

**Comment by dharabor** [comment]
Thank you Nir!
